// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmitSquareMap():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function IsGameOver():Promise<boolean|string>;

export function LatestBestMove():Promise<string>;
