// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmitSquareMap() {
  return window['go']['main']['App']['EmitSquareMap']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsGameOver() {
  return window['go']['main']['App']['IsGameOver']();
}

export function LatestBestMove() {
  return window['go']['main']['App']['LatestBestMove']();
}
