package bitboardchess

import (
	"errors"
	"strconv"
	"strings"
)

type Bitboard uint64

type Board struct {
	WhitePawns   Bitboard
	WhiteKnights Bitboard
	WhiteBishops Bitboard
	WhiteRooks   Bitboard
	WhiteQueens  Bitboard
	WhiteKing    Bitboard

	BlackPawns   Bitboard
	BlackKnights Bitboard
	BlackBishops Bitboard
	BlackRooks   Bitboard
	BlackQueens  Bitboard
	BlackKing    Bitboard

	castleRights   uint8
	enPassant      uint8
	halfmoveCount  uint8
	fullmoveNumber uint8
	turn           bool
}

// The function takes a move and applies that move to the board and returns the new board state. The function does not validate the move's legality and therefore
// should only be used with moves generated by the move generation function to ensure correctness.
func (b *Board) Update(m Move) (Board, error) {
	if b == nil {
		return Board{}, errors.New("board is nil")
	}

	// Keep validation constant-time and branch-light.
	if m.From > 63 || m.To > 63 {
		return Board{}, errors.New("move square out of range")
	}
	if m.PieceType < piecePawn || m.PieceType > pieceKing {
		return Board{}, errors.New("invalid piece type")
	}
	if m.promoteTo != 0 && (m.promoteTo < pieceKnight || m.promoteTo > pieceQueen) {
		return Board{}, errors.New("invalid promotion piece type")
	}

	originalTurn := b.turn
	nextBoard := applyMove(*b, m)

	// Halfmove clock resets on pawn move or capture, otherwise it increments.
	if m.PieceType == piecePawn || m.isCapture {
		nextBoard.halfmoveCount = 0
	}

	// Fullmove number increments after Black completes a move.
	if !originalTurn && nextBoard.fullmoveNumber < 255 {
		nextBoard.fullmoveNumber++
	}

	*b = nextBoard
	return nextBoard, nil

}

// getBitboards returns the bitboards for all pieces;
// In order:WhitePawns, WhiteKnights, WhiteBishops, WhiteRooks, WhiteQueens, WhiteKing, BlackPawns, BlackKnights, BlackBishops, BlackRooks, BlackQueens, BlackKing
func (b *Board) GetBitboards() [12]Bitboard {
	return [12]Bitboard{
		b.WhitePawns, b.WhiteKnights, b.WhiteBishops, b.WhiteRooks, b.WhiteQueens, b.WhiteKing,
		b.BlackPawns, b.BlackKnights, b.BlackBishops, b.BlackRooks, b.BlackQueens, b.BlackKing,
	}
}

// Takes an fen string and initializes the board state accordingly
func NewBoardFromFEN(fen string) *Board {
	parts := strings.Fields(fen)
	if len(parts) != 6 {
		return nil // Invalid FEN format
	}

	b := &Board{}

	// Parse piece placement (part 0)
	ranks := strings.Split(parts[0], "/")
	if len(ranks) != 8 {
		return nil
	}

	for rankIdx, rank := range ranks {
		fileIdx := 0
		for _, ch := range rank {
			if ch >= '1' && ch <= '8' {
				// Empty squares
				fileIdx += int(ch - '0')
			} else {
				// Map FEN rank index to bitboard square
				// rankIdx 0 = FEN rank 8 (squares 56-63)
				// rankIdx 7 = FEN rank 1 (squares 0-7)
				sq := (7-rankIdx)*8 + fileIdx
				bb := Bitboard(uint64(1) << sq)

				switch ch {
				case 'P':
					b.WhitePawns |= bb
				case 'N':
					b.WhiteKnights |= bb
				case 'B':
					b.WhiteBishops |= bb
				case 'R':
					b.WhiteRooks |= bb
				case 'Q':
					b.WhiteQueens |= bb
				case 'K':
					b.WhiteKing |= bb
				case 'p':
					b.BlackPawns |= bb
				case 'n':
					b.BlackKnights |= bb
				case 'b':
					b.BlackBishops |= bb
				case 'r':
					b.BlackRooks |= bb
				case 'q':
					b.BlackQueens |= bb
				case 'k':
					b.BlackKing |= bb
				}
				fileIdx++
			}
		}
	}

	// Parse active color (part 1)
	b.turn = parts[1] == "w" // true for white, false for black

	// Parse castling rights (part 2)
	castling := parts[2]
	b.castleRights = 0
	if strings.Contains(castling, "K") {
		b.castleRights |= 1 << 0 // castleWhiteKing
	}
	if strings.Contains(castling, "Q") {
		b.castleRights |= 1 << 1 // castleWhiteQueen
	}
	if strings.Contains(castling, "k") {
		b.castleRights |= 1 << 2 // castleBlackKing
	}
	if strings.Contains(castling, "q") {
		b.castleRights |= 1 << 3 // castleBlackQueen
	}

	// Parse en passant target square (part 3)
	epStr := parts[3]
	b.enPassant = 64 // 64 means no en passant
	if epStr != "-" && len(epStr) == 2 {
		file := int(epStr[0] - 'a')
		rank := int(epStr[1] - '1')
		if file >= 0 && file < 8 && rank >= 0 && rank < 8 {
			b.enPassant = uint8(rank*8 + file)
		}
	}

	// Parse halfmove clock (part 4)
	halfMove := 0
	if n, err := strconv.Atoi(parts[4]); err == nil {
		halfMove = n
	}
	if halfMove > 255 {
		halfMove = 255
	}
	b.halfmoveCount = uint8(halfMove)

	// Parse fullmove number (part 5)
	fullMove := 1
	if n, err := strconv.Atoi(parts[5]); err == nil {
		fullMove = n
	}
	if fullMove > 255 {
		fullMove = 255
	}
	b.fullmoveNumber = uint8(fullMove)

	return b
}
