package bitboardchess

import "math/bits"

const (
	piecePawn uint8 = iota + 1
	pieceKnight
	pieceBishop
	pieceRook
	pieceQueen
	pieceKing
)

const (
	castleWhiteKing uint8 = 1 << iota
	castleWhiteQueen
	castleBlackKing
	castleBlackQueen
)

const noEnPassant uint8 = 64

// Hot-path tuning flags.
// Setting this to false skips per-move post-annotation for check flags,
// which removes an expensive extra pass over generated moves.
const annotateChecksInMoveGen = false
const useHybridMoveGeneration = false

var (
	rookMasks   [64]Bitboard
	bishopMasks [64]Bitboard

	rookRelevantBits   [64]uint8
	bishopRelevantBits [64]uint8

	// These are generated by script output and can be replaced for pure multiply indexing.
	rookMagics   [64]uint64
	bishopMagics [64]uint64

	rookOffsets   [64]int
	bishopOffsets [64]int

	rookAttackTable   []Bitboard
	bishopAttackTable []Bitboard

	// Precomputed relevant-mask square lists for fast occupancy indexing when
	// magic multipliers are unavailable (Generated*Magics are zero).
	rookMaskSquares   [64][12]uint8
	bishopMaskSquares [64][9]uint8

	lineMaskTable [64][64]Bitboard
)

func init() {
	if !loadGeneratedMagicTables() {
		initSlidingMasks()
		initSlidingAttackTables()
	}
	initLineMasks()
}

func loadGeneratedMagicTables() bool {
	if len(GeneratedRookAttackTable) == 0 || len(GeneratedBishopAttackTable) == 0 {
		return false
	}

	copy(rookMasks[:], GeneratedRookMasks[:])
	copy(bishopMasks[:], GeneratedBishopMasks[:])
	copy(rookMagics[:], GeneratedRookMagics[:])
	copy(bishopMagics[:], GeneratedBishopMagics[:])

	for sq := 0; sq < 64; sq++ {
		rookRelevantBits[sq] = uint8(bits.OnesCount64(uint64(rookMasks[sq])))
		bishopRelevantBits[sq] = uint8(bits.OnesCount64(uint64(bishopMasks[sq])))
		rookOffsets[sq] = GeneratedRookOffsets[sq]
		bishopOffsets[sq] = GeneratedBishopOffsets[sq]
	}

	rookAttackTable = make([]Bitboard, len(GeneratedRookAttackTable))
	bishopAttackTable = make([]Bitboard, len(GeneratedBishopAttackTable))
	copy(rookAttackTable, GeneratedRookAttackTable)
	copy(bishopAttackTable, GeneratedBishopAttackTable)

	return true
}

// GenerateValidMoves performs direct legal move generation.
// It computes checks, pins, and legal response masks first, then generates moves
// per piece type without a full pseudo-legal generate-and-filter pass.
func GenerateValidMoves(board Board) []Move {
	return GenerateValidMovesInto(board, nil)
}

// GenerateValidMovesInto generates legal moves into a caller-provided buffer.
// Reusing this buffer in search loops avoids repeated allocations.
func GenerateValidMovesInto(board Board, moveBuffer []Move) []Move {
	var moves []Move
	if cap(moveBuffer) >= 64 {
		moves = moveBuffer[:0]
	} else {
		moves = make([]Move, 0, 64)
	}

	whiteToMove := board.turn
	whitePieces, blackPieces, allPieces := occupancy(board)
	ownPieces := blackPieces
	enemyPieces := whitePieces
	if whiteToMove {
		ownPieces = whitePieces
		enemyPieces = blackPieces
	}

	kingSquareIndex := kingSquare(board, whiteToMove)
	if kingSquareIndex < 0 {
		return moves
	}

	checkers := computeCheckers(board, whiteToMove, kingSquareIndex, allPieces)
	checkCount := bits.OnesCount64(uint64(checkers))
	var pinRays [64]Bitboard
	pinRaysPtr := (*[64]Bitboard)(nil)
	if !useHybridMoveGeneration {
		pinRaysPtr = &pinRays
	}
	pinnedPieces := computePinnedPieces(board, whiteToMove, kingSquareIndex, allPieces, pinRaysPtr)

	// Under single check, non-king moves must either capture the checker or block the check ray.
	checkMask := Bitboard(^uint64(0))
	if checkCount == 1 {
		checkerSquareIndex := bits.TrailingZeros64(uint64(checkers))
		checkMask = bbFromSquare(checkerSquareIndex)
		if isSliderPieceAt(board, checkerSquareIndex, !whiteToMove) {
			checkMask |= betweenMask(kingSquareIndex, checkerSquareIndex)
		}
	}

	moves = generateKingMoves(board, moves, whiteToMove, kingSquareIndex, ownPieces, allPieces, checkCount)
	if checkCount >= 2 {
		// In double check, only king moves are legal.
		if annotateChecksInMoveGen {
			annotateChecks(board, moves)
		}
		return moves
	}

	if useHybridMoveGeneration {
		// Hybrid strategy:
		// 1) Generate non-king pseudo-legal moves quickly without pin-ray masking.
		// 2) Selectively validate only risky moves (pinned and en-passant) by simulation.
		moves = generatePawnMoves(board, moves, whiteToMove, ownPieces, enemyPieces, allPieces, 0, nil, checkMask, checkers, checkCount)
		moves = generateKnightMoves(board, moves, whiteToMove, ownPieces, enemyPieces, 0, nil, checkMask)
		moves = generateSlidingMoves(board, moves, whiteToMove, ownPieces, enemyPieces, allPieces, pieceBishop, 0, nil, checkMask)
		moves = generateSlidingMoves(board, moves, whiteToMove, ownPieces, enemyPieces, allPieces, pieceRook, 0, nil, checkMask)
		moves = generateSlidingMoves(board, moves, whiteToMove, ownPieces, enemyPieces, allPieces, pieceQueen, 0, nil, checkMask)

		moves = filterRiskyPseudoMoves(board, moves, pinnedPieces)
	} else {
		moves = generatePawnMoves(board, moves, whiteToMove, ownPieces, enemyPieces, allPieces, pinnedPieces, &pinRays, checkMask, checkers, checkCount)
		moves = generateKnightMoves(board, moves, whiteToMove, ownPieces, enemyPieces, pinnedPieces, &pinRays, checkMask)
		moves = generateSlidingMoves(board, moves, whiteToMove, ownPieces, enemyPieces, allPieces, pieceBishop, pinnedPieces, &pinRays, checkMask)
		moves = generateSlidingMoves(board, moves, whiteToMove, ownPieces, enemyPieces, allPieces, pieceRook, pinnedPieces, &pinRays, checkMask)
		moves = generateSlidingMoves(board, moves, whiteToMove, ownPieces, enemyPieces, allPieces, pieceQueen, pinnedPieces, &pinRays, checkMask)
	}

	if annotateChecksInMoveGen {
		annotateChecks(board, moves)
	}
	return moves
}

func filterRiskyPseudoMoves(board Board, moves []Move, pinnedPieces Bitboard) []Move {
	kept := moves[:0]
	for _, move := range moves {
		fromBitboard := bbFromSquare(int(move.From))
		requiresLegalityCheck := move.PieceType == pieceKing || move.isEnPassant || (pinnedPieces&fromBitboard) != 0
		if !requiresLegalityCheck {
			kept = append(kept, move)
			continue
		}

		nextBoard := applyMove(board, move)
		if !isKingInCheckForSide(nextBoard, board.turn) {
			kept = append(kept, move)
		}
	}
	return kept
}

// generatePawnMoves handles pushes, captures, promotions, and en passant,
// while enforcing check masks and pin constraints.
func generatePawnMoves(
	board Board,
	moves []Move,
	whiteToMove bool,
	ownPieces Bitboard,
	enemyPieces Bitboard,
	allPieces Bitboard,
	pinnedPieces Bitboard,
	pinRays *[64]Bitboard,
	checkMask Bitboard,
	checkers Bitboard,
	checkCount int,
) []Move {
	var pawns Bitboard
	if whiteToMove {
		pawns = board.WhitePawns
	} else {
		pawns = board.BlackPawns
	}

	for pawnBitboard := pawns; pawnBitboard != 0; {
		fromSquare := popLSB(&pawnBitboard)
		fromSquareBitboard := bbFromSquare(fromSquare)
		isPinned := pinnedPieces&fromSquareBitboard != 0
		pinMask := Bitboard(^uint64(0))
		if isPinned {
			pinMask = pinRays[fromSquare]
		}

		if whiteToMove {
			toSquare := fromSquare + 8
			if toSquare < 64 {
				toSquareBitboard := bbFromSquare(toSquare)
				if allPieces&toSquareBitboard == 0 {
					if checkMask&toSquareBitboard != 0 && pinMask&toSquareBitboard != 0 {
						if toSquare >= 56 {
							moves = appendPromotionMoves(moves, fromSquare, toSquare, false)
						} else {
							moves = append(moves, Move{From: uint8(fromSquare), To: uint8(toSquare), PieceType: piecePawn})
						}
					}

					if fromSquare >= 8 && fromSquare <= 15 {
						doublePushSquare := fromSquare + 16
						doublePushSquareBitboard := bbFromSquare(doublePushSquare)
						if allPieces&doublePushSquareBitboard == 0 && checkMask&doublePushSquareBitboard != 0 && pinMask&doublePushSquareBitboard != 0 {
							moves = append(moves, Move{From: uint8(fromSquare), To: uint8(doublePushSquare), PieceType: piecePawn})
						}
					}
				}
			}

			captureTargets := PawnAttacksWhite[fromSquare] & enemyPieces
			if isPinned {
				captureTargets &= pinMask
			}
			captureTargets &= checkMask
			for remainingCaptures := captureTargets; remainingCaptures != 0; {
				toSquare := popLSB(&remainingCaptures)
				if toSquare >= 56 {
					moves = appendPromotionMoves(moves, fromSquare, toSquare, true)
				} else {
					moves = append(moves, Move{From: uint8(fromSquare), To: uint8(toSquare), PieceType: piecePawn, isCapture: true})
				}
			}
		} else {
			toSquare := fromSquare - 8
			if toSquare >= 0 {
				toSquareBitboard := bbFromSquare(toSquare)
				if allPieces&toSquareBitboard == 0 {
					if checkMask&toSquareBitboard != 0 && pinMask&toSquareBitboard != 0 {
						if toSquare <= 7 {
							moves = appendPromotionMoves(moves, fromSquare, toSquare, false)
						} else {
							moves = append(moves, Move{From: uint8(fromSquare), To: uint8(toSquare), PieceType: piecePawn})
						}
					}

					if fromSquare >= 48 && fromSquare <= 55 {
						doublePushSquare := fromSquare - 16
						doublePushSquareBitboard := bbFromSquare(doublePushSquare)
						if allPieces&doublePushSquareBitboard == 0 && checkMask&doublePushSquareBitboard != 0 && pinMask&doublePushSquareBitboard != 0 {
							moves = append(moves, Move{From: uint8(fromSquare), To: uint8(doublePushSquare), PieceType: piecePawn})
						}
					}
				}
			}

			captureTargets := PawnAttacksBlack[fromSquare] & enemyPieces
			if isPinned {
				captureTargets &= pinMask
			}
			captureTargets &= checkMask
			for remainingCaptures := captureTargets; remainingCaptures != 0; {
				toSquare := popLSB(&remainingCaptures)
				if toSquare <= 7 {
					moves = appendPromotionMoves(moves, fromSquare, toSquare, true)
				} else {
					moves = append(moves, Move{From: uint8(fromSquare), To: uint8(toSquare), PieceType: piecePawn, isCapture: true})
				}
			}
		}

		if board.enPassant < 64 {
			enPassantSquare := int(board.enPassant)
			enPassantSquareBitboard := bbFromSquare(enPassantSquare)
			if pinMask&enPassantSquareBitboard == 0 {
				continue
			}

			var canCaptureEnPassant bool
			if whiteToMove {
				canCaptureEnPassant = PawnAttacksWhite[fromSquare]&enPassantSquareBitboard != 0
			} else {
				canCaptureEnPassant = PawnAttacksBlack[fromSquare]&enPassantSquareBitboard != 0
			}
			if !canCaptureEnPassant {
				continue
			}

			capturedPawnSquare := enPassantSquare - 8
			if !whiteToMove {
				capturedPawnSquare = enPassantSquare + 8
			}

			if checkCount == 1 && (checkers&bbFromSquare(capturedPawnSquare) == 0) {
				continue
			}
			if checkCount == 1 && checkMask&enPassantSquareBitboard == 0 && checkers&bbFromSquare(capturedPawnSquare) == 0 {
				continue
			}

			move := Move{
				From:        uint8(fromSquare),
				To:          uint8(enPassantSquare),
				PieceType:   piecePawn,
				isCapture:   true,
				isEnPassant: true,
			}
			nextBoard := applyMove(board, move)
			if !isKingInCheckForSide(nextBoard, whiteToMove) {
				moves = append(moves, move)
			}
		}
	}

	_ = ownPieces
	return moves
}

// generateKnightMoves generates legal knight moves.
// Knights cannot move at all when pinned because their move pattern is non-linear.
func generateKnightMoves(
	board Board,
	moves []Move,
	whiteToMove bool,
	ownPieces Bitboard,
	enemyPieces Bitboard,
	pinnedPieces Bitboard,
	pinRays *[64]Bitboard,
	checkMask Bitboard,
) []Move {
	var knights Bitboard
	if whiteToMove {
		knights = board.WhiteKnights
	} else {
		knights = board.BlackKnights
	}

	for knightBitboard := knights; knightBitboard != 0; {
		fromSquare := popLSB(&knightBitboard)
		fromSquareBitboard := bbFromSquare(fromSquare)
		if pinnedPieces&fromSquareBitboard != 0 {
			continue
		}

		attackTargets := KnightAttacks[fromSquare] &^ ownPieces
		attackTargets &= checkMask
		for remainingTargets := attackTargets; remainingTargets != 0; {
			toSquare := popLSB(&remainingTargets)
			toSquareBitboard := bbFromSquare(toSquare)
			moves = append(moves, Move{
				From:      uint8(fromSquare),
				To:        uint8(toSquare),
				PieceType: pieceKnight,
				isCapture: enemyPieces&toSquareBitboard != 0,
			})
		}
	}

	_ = pinRays
	return moves
}

// generateSlidingMoves handles bishops, rooks, and queens with precomputed sliding attacks.
// Pinned sliders are restricted to their king-line pin ray.
func generateSlidingMoves(
	board Board,
	moves []Move,
	whiteToMove bool,
	ownPieces Bitboard,
	enemyPieces Bitboard,
	allPieces Bitboard,
	pieceType uint8,
	pinnedPieces Bitboard,
	pinRays *[64]Bitboard,
	checkMask Bitboard,
) []Move {
	var pieceBitboard Bitboard
	if whiteToMove {
		switch pieceType {
		case pieceBishop:
			pieceBitboard = board.WhiteBishops
		case pieceRook:
			pieceBitboard = board.WhiteRooks
		case pieceQueen:
			pieceBitboard = board.WhiteQueens
		}
	} else {
		switch pieceType {
		case pieceBishop:
			pieceBitboard = board.BlackBishops
		case pieceRook:
			pieceBitboard = board.BlackRooks
		case pieceQueen:
			pieceBitboard = board.BlackQueens
		}
	}

	for remainingPieces := pieceBitboard; remainingPieces != 0; {
		fromSquare := popLSB(&remainingPieces)
		fromSquareBitboard := bbFromSquare(fromSquare)

		var attackTargets Bitboard
		switch pieceType {
		case pieceBishop:
			attackTargets = BishopAttacks(fromSquare, allPieces)
		case pieceRook:
			attackTargets = RookAttacks(fromSquare, allPieces)
		case pieceQueen:
			attackTargets = QueenAttacks(fromSquare, allPieces)
		}

		attackTargets &= ^ownPieces
		attackTargets &= checkMask
		if pinnedPieces&fromSquareBitboard != 0 {
			attackTargets &= pinRays[fromSquare]
		}

		for remainingTargets := attackTargets; remainingTargets != 0; {
			toSquare := popLSB(&remainingTargets)
			toSquareBitboard := bbFromSquare(toSquare)
			moves = append(moves, Move{
				From:      uint8(fromSquare),
				To:        uint8(toSquare),
				PieceType: pieceType,
				isCapture: enemyPieces&toSquareBitboard != 0,
			})
		}
	}

	return moves
}

// generateKingMoves creates legal king moves and legal castling moves.
// Every destination is validated against enemy attacks on the resulting board.
func generateKingMoves(
	board Board,
	moves []Move,
	whiteToMove bool,
	kingSquareIndex int,
	ownPieces Bitboard,
	allPieces Bitboard,
	checkCount int,
) []Move {
	enemyIsWhite := !whiteToMove
	kingTargets := KingAttacks[kingSquareIndex] &^ ownPieces
	fromSquareBitboard := bbFromSquare(kingSquareIndex)
	for remainingKingTargets := kingTargets; remainingKingTargets != 0; {
		toSquare := popLSB(&remainingKingTargets)
		move := Move{From: uint8(kingSquareIndex), To: uint8(toSquare), PieceType: pieceKing}
		if allPieces&bbFromSquare(toSquare) != 0 {
			move.isCapture = true
		}
		nextBoard := simulateKingMove(board, whiteToMove, kingSquareIndex, toSquare, move.isCapture)
		nextOccupancy := (allPieces &^ fromSquareBitboard) | bbFromSquare(toSquare)
		if !isSquareAttackedWithOccupancy(toSquare, enemyIsWhite, nextBoard, nextOccupancy) {
			moves = append(moves, move)
		}
	}

	if checkCount != 0 {
		return moves
	}

	// Castling is legal only if rights are present, path is clear,
	// and the king does not pass through attacked squares.
	if whiteToMove {
		if board.castleRights&castleWhiteKing != 0 {
			if allPieces&(bbFromSquare(5)|bbFromSquare(6)) == 0 &&
				!IsSquareAttacked(4, true, board) &&
				!IsSquareAttacked(5, true, board) &&
				!IsSquareAttacked(6, true, board) {
				moves = append(moves, Move{From: 4, To: 6, PieceType: pieceKing, isCastle: true})
			}
		}
		if board.castleRights&castleWhiteQueen != 0 {
			if allPieces&(bbFromSquare(1)|bbFromSquare(2)|bbFromSquare(3)) == 0 &&
				!IsSquareAttacked(4, true, board) &&
				!IsSquareAttacked(3, true, board) &&
				!IsSquareAttacked(2, true, board) {
				moves = append(moves, Move{From: 4, To: 2, PieceType: pieceKing, isCastle: true})
			}
		}
	} else {
		if board.castleRights&castleBlackKing != 0 {
			if allPieces&(bbFromSquare(61)|bbFromSquare(62)) == 0 &&
				!IsSquareAttacked(60, false, board) &&
				!IsSquareAttacked(61, false, board) &&
				!IsSquareAttacked(62, false, board) {
				moves = append(moves, Move{From: 60, To: 62, PieceType: pieceKing, isCastle: true})
			}
		}
		if board.castleRights&castleBlackQueen != 0 {
			if allPieces&(bbFromSquare(57)|bbFromSquare(58)|bbFromSquare(59)) == 0 &&
				!IsSquareAttacked(60, false, board) &&
				!IsSquareAttacked(59, false, board) &&
				!IsSquareAttacked(58, false, board) {
				moves = append(moves, Move{From: 60, To: 58, PieceType: pieceKing, isCastle: true})
			}
		}
	}

	return moves
}

// computeCheckers returns all enemy pieces currently giving check to the side-to-move king.
func computeCheckers(board Board, whiteKing bool, kingSquareIndex int, occupancy Bitboard) Bitboard {
	var checkers Bitboard
	if whiteKing {
		checkers |= PawnAttacksWhite[kingSquareIndex] & board.BlackPawns
		checkers |= KnightAttacks[kingSquareIndex] & board.BlackKnights
		checkers |= BishopAttacks(kingSquareIndex, occupancy) & (board.BlackBishops | board.BlackQueens)
		checkers |= RookAttacks(kingSquareIndex, occupancy) & (board.BlackRooks | board.BlackQueens)
		checkers |= KingAttacks[kingSquareIndex] & board.BlackKing
	} else {
		checkers |= PawnAttacksBlack[kingSquareIndex] & board.WhitePawns
		checkers |= KnightAttacks[kingSquareIndex] & board.WhiteKnights
		checkers |= BishopAttacks(kingSquareIndex, occupancy) & (board.WhiteBishops | board.WhiteQueens)
		checkers |= RookAttacks(kingSquareIndex, occupancy) & (board.WhiteRooks | board.WhiteQueens)
		checkers |= KingAttacks[kingSquareIndex] & board.WhiteKing
	}
	return checkers
}

// computePinnedPieces finds own pieces pinned to the king and their legal pin rays.
func computePinnedPieces(board Board, whiteKing bool, kingSquareIndex int, allPieces Bitboard, pinRays *[64]Bitboard) Bitboard {
	var pinned Bitboard

	directions := [8][2]int{
		{1, 0}, {-1, 0}, {0, 1}, {0, -1},
		{1, 1}, {1, -1}, {-1, 1}, {-1, -1},
	}

	for _, direction := range directions {
		file := fileOf(kingSquareIndex) + direction[0]
		rank := rankOf(kingSquareIndex) + direction[1]
		candidateSquare := -1
		for onBoard(file, rank) {
			square := rank*8 + file
			squareBitboard := bbFromSquare(square)
			if allPieces&squareBitboard != 0 {
				if candidateSquare == -1 {
					if isOwnPieceAt(board, square, whiteKing) {
						candidateSquare = square
					} else {
						break
					}
				} else {
					if isEnemySliderForDir(board, square, whiteKing, direction[0], direction[1]) {
						candidateBitboard := bbFromSquare(candidateSquare)
						pinned |= candidateBitboard
						if pinRays != nil {
							pinRays[candidateSquare] = lineMaskTable[kingSquareIndex][square] &^ bbFromSquare(kingSquareIndex)
						}
					}
					break
				}
			}
			file += direction[0]
			rank += direction[1]
		}
	}

	return pinned
}

// IsSquareAttacked returns true when the given side attacks the target square
// in the current board position.
func IsSquareAttacked(square int, byWhite bool, board Board) bool {
	_, _, occupancyBitboard := occupancy(board)
	return isSquareAttackedWithOccupancy(square, byWhite, board, occupancyBitboard)
}

func isSquareAttackedWithOccupancy(square int, byWhite bool, board Board, occupancyBitboard Bitboard) bool {
	if byWhite {
		if PawnAttacksBlack[square]&board.WhitePawns != 0 {
			return true
		}
		if KnightAttacks[square]&board.WhiteKnights != 0 {
			return true
		}
		if BishopAttacks(square, occupancyBitboard)&(board.WhiteBishops|board.WhiteQueens) != 0 {
			return true
		}
		if RookAttacks(square, occupancyBitboard)&(board.WhiteRooks|board.WhiteQueens) != 0 {
			return true
		}
		return KingAttacks[square]&board.WhiteKing != 0
	}

	if PawnAttacksWhite[square]&board.BlackPawns != 0 {
		return true
	}
	if KnightAttacks[square]&board.BlackKnights != 0 {
		return true
	}
	if BishopAttacks(square, occupancyBitboard)&(board.BlackBishops|board.BlackQueens) != 0 {
		return true
	}
	if RookAttacks(square, occupancyBitboard)&(board.BlackRooks|board.BlackQueens) != 0 {
		return true
	}
	return KingAttacks[square]&board.BlackKing != 0
}

func BishopAttacks(square int, occupancy Bitboard) Bitboard {
	mask := bishopMasks[square]
	maskedOccupancy := occupancy & mask
	var attackTableIndex int
	if bishopMagics[square] != 0 {
		attackTableIndex = int((uint64(maskedOccupancy) * bishopMagics[square]) >> (64 - bishopRelevantBits[square]))
	} else {
		attackTableIndex = bishopOccupancyToIndex(square, maskedOccupancy)
	}
	return bishopAttackTable[bishopOffsets[square]+attackTableIndex]
}

func RookAttacks(square int, occupancy Bitboard) Bitboard {
	mask := rookMasks[square]
	maskedOccupancy := occupancy & mask
	var attackTableIndex int
	if rookMagics[square] != 0 {
		attackTableIndex = int((uint64(maskedOccupancy) * rookMagics[square]) >> (64 - rookRelevantBits[square]))
	} else {
		attackTableIndex = rookOccupancyToIndex(square, maskedOccupancy)
	}
	return rookAttackTable[rookOffsets[square]+attackTableIndex]
}

func rookOccupancyToIndex(square int, maskedOccupancy Bitboard) int {
	index := 0
	for bitIndex := uint8(0); bitIndex < rookRelevantBits[square]; bitIndex++ {
		squareIndex := rookMaskSquares[square][bitIndex]
		if (maskedOccupancy & bbFromSquare(int(squareIndex))) != 0 {
			index |= 1 << bitIndex
		}
	}
	return index
}

func bishopOccupancyToIndex(square int, maskedOccupancy Bitboard) int {
	index := 0
	for bitIndex := uint8(0); bitIndex < bishopRelevantBits[square]; bitIndex++ {
		squareIndex := bishopMaskSquares[square][bitIndex]
		if (maskedOccupancy & bbFromSquare(int(squareIndex))) != 0 {
			index |= 1 << bitIndex
		}
	}
	return index
}

func QueenAttacks(square int, occupancy Bitboard) Bitboard {
	return BishopAttacks(square, occupancy) | RookAttacks(square, occupancy)
}

func initSlidingMasks() {
	for sq := 0; sq < 64; sq++ {
		rookMasks[sq] = rookMask(sq)
		bishopMasks[sq] = bishopMask(sq)
		rookRelevantBits[sq] = uint8(bits.OnesCount64(uint64(rookMasks[sq])))
		bishopRelevantBits[sq] = uint8(bits.OnesCount64(uint64(bishopMasks[sq])))

		tempRookMask := rookMasks[sq]
		for bitIndex := 0; tempRookMask != 0; bitIndex++ {
			maskSquare := bits.TrailingZeros64(uint64(tempRookMask))
			rookMaskSquares[sq][bitIndex] = uint8(maskSquare)
			tempRookMask &= tempRookMask - 1
		}

		tempBishopMask := bishopMasks[sq]
		for bitIndex := 0; tempBishopMask != 0; bitIndex++ {
			maskSquare := bits.TrailingZeros64(uint64(tempBishopMask))
			bishopMaskSquares[sq][bitIndex] = uint8(maskSquare)
			tempBishopMask &= tempBishopMask - 1
		}
	}
}

func initSlidingAttackTables() {
	rookTotal := 0
	bishopTotal := 0
	for sq := 0; sq < 64; sq++ {
		rookOffsets[sq] = rookTotal
		bishopOffsets[sq] = bishopTotal
		rookTotal += 1 << rookRelevantBits[sq]
		bishopTotal += 1 << bishopRelevantBits[sq]
	}

	rookAttackTable = make([]Bitboard, rookTotal)
	bishopAttackTable = make([]Bitboard, bishopTotal)

	for sq := 0; sq < 64; sq++ {
		mask := rookMasks[sq]
		subsets := 1 << rookRelevantBits[sq]
		for idx := 0; idx < subsets; idx++ {
			occ := indexToOccupancy(idx, mask)
			rookAttackTable[rookOffsets[sq]+idx] = rookAttacksOnTheFly(sq, occ)
		}

		mask = bishopMasks[sq]
		subsets = 1 << bishopRelevantBits[sq]
		for idx := 0; idx < subsets; idx++ {
			occ := indexToOccupancy(idx, mask)
			bishopAttackTable[bishopOffsets[sq]+idx] = bishopAttacksOnTheFly(sq, occ)
		}
	}
}

func initLineMasks() {
	for a := 0; a < 64; a++ {
		for b := 0; b < 64; b++ {
			lineMaskTable[a][b] = lineMask(a, b)
		}
	}
}

// annotateChecks marks moves that give check in the resulting position.
func annotateChecks(board Board, moves []Move) {
	moverIsWhite := board.turn
	for moveIndex := range moves {
		nextBoard := applyMove(board, moves[moveIndex])
		enemyKingSquare := kingSquare(nextBoard, !moverIsWhite)
		if enemyKingSquare >= 0 && IsSquareAttacked(enemyKingSquare, moverIsWhite, nextBoard) {
			moves[moveIndex].isCheck = true
		}
	}
}

// applyMove updates board state for legality checks and check annotation.
// It is intentionally simple and not optimized as a full search make/unmake.
func applyMove(board Board, move Move) Board {
	nextBoard := board
	nextBoard.enPassant = noEnPassant

	whiteToMove := board.turn

	removePieceAt(&nextBoard, int(move.From))

	if move.isEnPassant {
		capturedPawnSquare := int(move.To) - 8
		if !whiteToMove {
			capturedPawnSquare = int(move.To) + 8
		}
		removePieceAt(&nextBoard, capturedPawnSquare)
	} else if move.isCapture {
		removePieceAt(&nextBoard, int(move.To))
	}

	pieceToPlace := move.PieceType
	if move.PieceType == piecePawn && move.promoteTo != 0 {
		pieceToPlace = move.promoteTo
	}
	addPieceAt(&nextBoard, int(move.To), whiteToMove, pieceToPlace)

	if move.isCastle {
		if whiteToMove {
			if move.To == 6 {
				removePieceAt(&nextBoard, 7)
				addPieceAt(&nextBoard, 5, true, pieceRook)
			} else if move.To == 2 {
				removePieceAt(&nextBoard, 0)
				addPieceAt(&nextBoard, 3, true, pieceRook)
			}
		} else {
			if move.To == 62 {
				removePieceAt(&nextBoard, 63)
				addPieceAt(&nextBoard, 61, false, pieceRook)
			} else if move.To == 58 {
				removePieceAt(&nextBoard, 56)
				addPieceAt(&nextBoard, 59, false, pieceRook)
			}
		}
	}

	if move.PieceType == piecePawn {
		if whiteToMove && int(move.To)-int(move.From) == 16 {
			nextBoard.enPassant = uint8(int(move.From) + 8)
		}
		if !whiteToMove && int(move.From)-int(move.To) == 16 {
			nextBoard.enPassant = uint8(int(move.From) - 8)
		}
	}

	if move.PieceType == pieceKing {
		if whiteToMove {
			nextBoard.castleRights &^= castleWhiteKing | castleWhiteQueen
		} else {
			nextBoard.castleRights &^= castleBlackKing | castleBlackQueen
		}
	}

	if move.PieceType == pieceRook {
		switch move.From {
		case 0:
			nextBoard.castleRights &^= castleWhiteQueen
		case 7:
			nextBoard.castleRights &^= castleWhiteKing
		case 56:
			nextBoard.castleRights &^= castleBlackQueen
		case 63:
			nextBoard.castleRights &^= castleBlackKing
		}
	}

	if move.isCapture {
		switch move.To {
		case 0:
			nextBoard.castleRights &^= castleWhiteQueen
		case 7:
			nextBoard.castleRights &^= castleWhiteKing
		case 56:
			nextBoard.castleRights &^= castleBlackQueen
		case 63:
			nextBoard.castleRights &^= castleBlackKing
		}
	}

	nextBoard.turn = !board.turn
	nextBoard.halfmoveCount++
	return nextBoard
}

func isKingInCheckForSide(b Board, white bool) bool {
	ksq := kingSquare(b, white)
	if ksq < 0 {
		return false
	}
	return IsSquareAttacked(ksq, !white, b)
}
func IsCheck(b Board) bool {
	return isKingInCheckForSide(b, b.turn)
}
func occupancy(b Board) (Bitboard, Bitboard, Bitboard) {
	white := b.WhitePawns | b.WhiteKnights | b.WhiteBishops | b.WhiteRooks | b.WhiteQueens | b.WhiteKing
	black := b.BlackPawns | b.BlackKnights | b.BlackBishops | b.BlackRooks | b.BlackQueens | b.BlackKing
	return white, black, white | black
}

func kingSquare(b Board, white bool) int {
	bb := b.BlackKing
	if white {
		bb = b.WhiteKing
	}
	if bb == 0 {
		return -1
	}
	return bits.TrailingZeros64(uint64(bb))
}

func isSliderPieceAt(b Board, sq int, white bool) bool {
	bb := bbFromSquare(sq)
	if white {
		return (b.WhiteBishops|b.WhiteRooks|b.WhiteQueens)&bb != 0
	}
	return (b.BlackBishops|b.BlackRooks|b.BlackQueens)&bb != 0
}

func isOwnPieceAt(b Board, sq int, white bool) bool {
	bb := bbFromSquare(sq)
	if white {
		return (b.WhitePawns|b.WhiteKnights|b.WhiteBishops|b.WhiteRooks|b.WhiteQueens|b.WhiteKing)&bb != 0
	}
	return (b.BlackPawns|b.BlackKnights|b.BlackBishops|b.BlackRooks|b.BlackQueens|b.BlackKing)&bb != 0
}

func isEnemySliderForDir(b Board, sq int, whiteKing bool, df int, dr int) bool {
	bb := bbFromSquare(sq)
	orthogonal := df == 0 || dr == 0
	if whiteKing {
		if orthogonal {
			return (b.BlackRooks|b.BlackQueens)&bb != 0
		}
		return (b.BlackBishops|b.BlackQueens)&bb != 0
	}
	if orthogonal {
		return (b.WhiteRooks|b.WhiteQueens)&bb != 0
	}
	return (b.WhiteBishops|b.WhiteQueens)&bb != 0
}

func appendPromotionMoves(moves []Move, from int, to int, capture bool) []Move {
	promos := [4]uint8{pieceQueen, pieceRook, pieceBishop, pieceKnight}
	for _, p := range promos {
		moves = append(moves, Move{
			From:      uint8(from),
			To:        uint8(to),
			PieceType: piecePawn,
			isCapture: capture,
			promoteTo: p,
		})
	}
	return moves
}

func removePieceAt(b *Board, sq int) {
	squareBitboard := bbFromSquare(sq)
	clearMask := ^squareBitboard

	if b.WhitePawns&squareBitboard != 0 {
		b.WhitePawns &= clearMask
		return
	}
	if b.WhiteKnights&squareBitboard != 0 {
		b.WhiteKnights &= clearMask
		return
	}
	if b.WhiteBishops&squareBitboard != 0 {
		b.WhiteBishops &= clearMask
		return
	}
	if b.WhiteRooks&squareBitboard != 0 {
		b.WhiteRooks &= clearMask
		return
	}
	if b.WhiteQueens&squareBitboard != 0 {
		b.WhiteQueens &= clearMask
		return
	}
	if b.WhiteKing&squareBitboard != 0 {
		b.WhiteKing &= clearMask
		return
	}

	if b.BlackPawns&squareBitboard != 0 {
		b.BlackPawns &= clearMask
		return
	}
	if b.BlackKnights&squareBitboard != 0 {
		b.BlackKnights &= clearMask
		return
	}
	if b.BlackBishops&squareBitboard != 0 {
		b.BlackBishops &= clearMask
		return
	}
	if b.BlackRooks&squareBitboard != 0 {
		b.BlackRooks &= clearMask
		return
	}
	if b.BlackQueens&squareBitboard != 0 {
		b.BlackQueens &= clearMask
		return
	}
	if b.BlackKing&squareBitboard != 0 {
		b.BlackKing &= clearMask
	}
}

// simulateKingMove applies only the pieceboard changes needed to validate king safety.
// It is intentionally minimal to keep king move legality checks fast.
func simulateKingMove(board Board, whiteToMove bool, fromSquare int, toSquare int, isCapture bool) Board {
	nextBoard := board
	fromBitboard := bbFromSquare(fromSquare)
	toBitboard := bbFromSquare(toSquare)

	if whiteToMove {
		nextBoard.WhiteKing &^= fromBitboard
		nextBoard.WhiteKing |= toBitboard
		if isCapture {
			clearBlackPieceAtMask(&nextBoard, toBitboard)
		}
	} else {
		nextBoard.BlackKing &^= fromBitboard
		nextBoard.BlackKing |= toBitboard
		if isCapture {
			clearWhitePieceAtMask(&nextBoard, toBitboard)
		}
	}

	return nextBoard
}

func clearWhitePieceAtMask(board *Board, mask Bitboard) {
	if board.WhitePawns&mask != 0 {
		board.WhitePawns &^= mask
		return
	}
	if board.WhiteKnights&mask != 0 {
		board.WhiteKnights &^= mask
		return
	}
	if board.WhiteBishops&mask != 0 {
		board.WhiteBishops &^= mask
		return
	}
	if board.WhiteRooks&mask != 0 {
		board.WhiteRooks &^= mask
		return
	}
	if board.WhiteQueens&mask != 0 {
		board.WhiteQueens &^= mask
		return
	}
	if board.WhiteKing&mask != 0 {
		board.WhiteKing &^= mask
	}
}

func clearBlackPieceAtMask(board *Board, mask Bitboard) {
	if board.BlackPawns&mask != 0 {
		board.BlackPawns &^= mask
		return
	}
	if board.BlackKnights&mask != 0 {
		board.BlackKnights &^= mask
		return
	}
	if board.BlackBishops&mask != 0 {
		board.BlackBishops &^= mask
		return
	}
	if board.BlackRooks&mask != 0 {
		board.BlackRooks &^= mask
		return
	}
	if board.BlackQueens&mask != 0 {
		board.BlackQueens &^= mask
		return
	}
	if board.BlackKing&mask != 0 {
		board.BlackKing &^= mask
	}
}

func addPieceAt(b *Board, sq int, white bool, piece uint8) {
	mask := bbFromSquare(sq)
	if white {
		switch piece {
		case piecePawn:
			b.WhitePawns |= mask
		case pieceKnight:
			b.WhiteKnights |= mask
		case pieceBishop:
			b.WhiteBishops |= mask
		case pieceRook:
			b.WhiteRooks |= mask
		case pieceQueen:
			b.WhiteQueens |= mask
		case pieceKing:
			b.WhiteKing |= mask
		}
		return
	}

	switch piece {
	case piecePawn:
		b.BlackPawns |= mask
	case pieceKnight:
		b.BlackKnights |= mask
	case pieceBishop:
		b.BlackBishops |= mask
	case pieceRook:
		b.BlackRooks |= mask
	case pieceQueen:
		b.BlackQueens |= mask
	case pieceKing:
		b.BlackKing |= mask
	}
}

func bbFromSquare(sq int) Bitboard {
	return Bitboard(uint64(1) << sq)
}

func popLSB(bb *Bitboard) int {
	sq := bits.TrailingZeros64(uint64(*bb))
	*bb &= *bb - 1
	return sq
}

func fileOf(sq int) int { return sq & 7 }
func rankOf(sq int) int { return sq >> 3 }
func onBoard(file int, rank int) bool {
	return file >= 0 && file < 8 && rank >= 0 && rank < 8
}

func lineMask(a int, b int) Bitboard {
	if a == b {
		return bbFromSquare(a)
	}
	fa, ra := fileOf(a), rankOf(a)
	fb, rb := fileOf(b), rankOf(b)
	df := fb - fa
	dr := rb - ra

	stepF := 0
	if df != 0 {
		if df > 0 {
			stepF = 1
		} else {
			stepF = -1
		}
	}

	stepR := 0
	if dr != 0 {
		if dr > 0 {
			stepR = 1
		} else {
			stepR = -1
		}
	}

	if df != 0 && dr != 0 && abs(df) != abs(dr) {
		return 0
	}
	if df == 0 && dr == 0 {
		return bbFromSquare(a)
	}

	var mask Bitboard
	f := fa
	r := ra
	for {
		sq := r*8 + f
		mask |= bbFromSquare(sq)
		if sq == b {
			break
		}
		f += stepF
		r += stepR
		if !onBoard(f, r) {
			return 0
		}
	}
	return mask
}

func betweenMask(a int, b int) Bitboard {
	line := lineMask(a, b)
	if line == 0 {
		return 0
	}
	line &^= bbFromSquare(a)
	line &^= bbFromSquare(b)
	return line
}

func abs(v int) int {
	if v < 0 {
		return -v
	}
	return v
}

func rookMask(square int) Bitboard {
	f := fileOf(square)
	r := rankOf(square)
	var mask Bitboard
	for rr := r + 1; rr <= 6; rr++ {
		mask |= bbFromSquare(rr*8 + f)
	}
	for rr := r - 1; rr >= 1; rr-- {
		mask |= bbFromSquare(rr*8 + f)
	}
	for ff := f + 1; ff <= 6; ff++ {
		mask |= bbFromSquare(r*8 + ff)
	}
	for ff := f - 1; ff >= 1; ff-- {
		mask |= bbFromSquare(r*8 + ff)
	}
	return mask
}

func bishopMask(square int) Bitboard {
	f := fileOf(square)
	r := rankOf(square)
	var mask Bitboard
	for ff, rr := f+1, r+1; ff <= 6 && rr <= 6; ff, rr = ff+1, rr+1 {
		mask |= bbFromSquare(rr*8 + ff)
	}
	for ff, rr := f-1, r+1; ff >= 1 && rr <= 6; ff, rr = ff-1, rr+1 {
		mask |= bbFromSquare(rr*8 + ff)
	}
	for ff, rr := f+1, r-1; ff <= 6 && rr >= 1; ff, rr = ff+1, rr-1 {
		mask |= bbFromSquare(rr*8 + ff)
	}
	for ff, rr := f-1, r-1; ff >= 1 && rr >= 1; ff, rr = ff-1, rr-1 {
		mask |= bbFromSquare(rr*8 + ff)
	}
	return mask
}

func rookAttacksOnTheFly(square int, blockers Bitboard) Bitboard {
	f := fileOf(square)
	r := rankOf(square)
	var attacks Bitboard
	for rr := r + 1; rr <= 7; rr++ {
		sq := rr*8 + f
		attacks |= bbFromSquare(sq)
		if blockers&bbFromSquare(sq) != 0 {
			break
		}
	}
	for rr := r - 1; rr >= 0; rr-- {
		sq := rr*8 + f
		attacks |= bbFromSquare(sq)
		if blockers&bbFromSquare(sq) != 0 {
			break
		}
	}
	for ff := f + 1; ff <= 7; ff++ {
		sq := r*8 + ff
		attacks |= bbFromSquare(sq)
		if blockers&bbFromSquare(sq) != 0 {
			break
		}
	}
	for ff := f - 1; ff >= 0; ff-- {
		sq := r*8 + ff
		attacks |= bbFromSquare(sq)
		if blockers&bbFromSquare(sq) != 0 {
			break
		}
	}
	return attacks
}

func bishopAttacksOnTheFly(square int, blockers Bitboard) Bitboard {
	f := fileOf(square)
	r := rankOf(square)
	var attacks Bitboard
	for ff, rr := f+1, r+1; ff <= 7 && rr <= 7; ff, rr = ff+1, rr+1 {
		sq := rr*8 + ff
		attacks |= bbFromSquare(sq)
		if blockers&bbFromSquare(sq) != 0 {
			break
		}
	}
	for ff, rr := f-1, r+1; ff >= 0 && rr <= 7; ff, rr = ff-1, rr+1 {
		sq := rr*8 + ff
		attacks |= bbFromSquare(sq)
		if blockers&bbFromSquare(sq) != 0 {
			break
		}
	}
	for ff, rr := f+1, r-1; ff <= 7 && rr >= 0; ff, rr = ff+1, rr-1 {
		sq := rr*8 + ff
		attacks |= bbFromSquare(sq)
		if blockers&bbFromSquare(sq) != 0 {
			break
		}
	}
	for ff, rr := f-1, r-1; ff >= 0 && rr >= 0; ff, rr = ff-1, rr-1 {
		sq := rr*8 + ff
		attacks |= bbFromSquare(sq)
		if blockers&bbFromSquare(sq) != 0 {
			break
		}
	}
	return attacks
}

func occupancyToIndex(occ Bitboard, mask Bitboard) int {
	idx := 0
	bit := 0
	for m := mask; m != 0; {
		sq := popLSB(&m)
		if occ&bbFromSquare(sq) != 0 {
			idx |= 1 << bit
		}
		bit++
	}
	return idx
}

func indexToOccupancy(index int, mask Bitboard) Bitboard {
	var occ Bitboard
	bit := 0
	for m := mask; m != 0; {
		sq := popLSB(&m)
		if index&(1<<bit) != 0 {
			occ |= bbFromSquare(sq)
		}
		bit++
	}
	return occ
}
