#!/usr/bin/env python3
"""Generate passed-pawn lookup tables for H1=LSB bitboard mapping.

This script emits two 64-entry tables:
1) PassedPawnMaskWhite[sq]: squares in front of a white pawn on sq on the same
   file and adjacent files.
2) PassedPawnMaskBlack[sq]: mirrored rule for black (toward rank 1).

Bitboard mapping used here:
- bit 0   = h1
- bit 7   = a1
- bit 56  = h8
- bit 63  = a8

Usage:
    # Paste-ready declarations (default; no package line)
    python scripts/generate_passed_pawn_tables.py

    # Full file mode (includes package line)
    python scripts/generate_passed_pawn_tables.py --include-package --package main > passed_pawn_tables.go
"""

from __future__ import annotations

import argparse


def sq_to_idx(file_: int, rank: int) -> int:
    """Convert (file, rank) to bit index for H1=LSB mapping.

    file_: 0..7 for a..h
    rank:  0..7 for 1..8
    """
    return rank * 8 + (7 - file_)


def idx_to_sq(idx: int) -> tuple[int, int]:
    """Convert bit index (H1=LSB) to (file, rank)."""
    rank = idx // 8
    file_ = 7 - (idx & 7)
    return file_, rank


def bb(idx: int) -> int:
    return 1 << idx


def passed_mask_white(idx: int) -> int:
    """Squares that must be clear of black pawns for white pawn at idx to pass.

    Includes all squares on same/adjacent files strictly ahead of the pawn,
    up to rank 8.
    """
    file_, rank = idx_to_sq(idx)
    out = 0
    for f in range(max(0, file_ - 1), min(7, file_ + 1) + 1):
        for r in range(rank + 1, 8):
            out |= bb(sq_to_idx(f, r))
    return out


def passed_mask_black(idx: int) -> int:
    """Squares that must be clear of white pawns for black pawn at idx to pass.

    Includes all squares on same/adjacent files strictly ahead of the pawn
    from Black's perspective (toward rank 1).
    """
    file_, rank = idx_to_sq(idx)
    out = 0
    for f in range(max(0, file_ - 1), min(7, file_ + 1) + 1):
        for r in range(0, rank):
            out |= bb(sq_to_idx(f, r))
    return out


def emit_u64_array(name: str, values: list[int]) -> None:
    print(f"var {name} = [64]uint64{{")
    for v in values:
        print(f"\t0x{v:016x},")
    print("}")
    print()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--package", default="main", help="Go package name")
    parser.add_argument(
        "--include-package",
        action="store_true",
        help="Emit a full Go file header (codegen comment + package line)",
    )
    args = parser.parse_args()

    # Sanity checks for requested mapping.
    assert sq_to_idx(7, 0) == 0   # h1
    assert sq_to_idx(0, 7) == 63  # a8

    white = [passed_mask_white(i) for i in range(64)]
    black = [passed_mask_black(i) for i in range(64)]

    if args.include_package:
        print("// Code generated by scripts/generate_passed_pawn_tables.py; DO NOT EDIT.")
        print(f"package {args.package}")
        print()
    emit_u64_array("PassedPawnMaskWhite", white)
    emit_u64_array("PassedPawnMaskBlack", black)


if __name__ == "__main__":
    main()
