#!/usr/bin/env python3
"""Generate Go bitboard attack tables for king, knight, and pawns.

Usage:
    python generate_attack_tables.py > generated_attack_tables.go
"""

from __future__ import annotations


def bb(sq: int) -> int:
    return 1 << sq


def file_of(sq: int) -> int:
    return sq & 7


def rank_of(sq: int) -> int:
    return sq >> 3


def on_board(file: int, rank: int) -> bool:
    return 0 <= file < 8 and 0 <= rank < 8


def king_attacks(sq: int) -> int:
    f = file_of(sq)
    r = rank_of(sq)
    out = 0
    for df in (-1, 0, 1):
        for dr in (-1, 0, 1):
            if df == 0 and dr == 0:
                continue
            nf = f + df
            nr = r + dr
            if on_board(nf, nr):
                out |= bb(nr * 8 + nf)
    return out


def knight_attacks(sq: int) -> int:
    f = file_of(sq)
    r = rank_of(sq)
    out = 0
    for df, dr in (
        (1, 2),
        (2, 1),
        (2, -1),
        (1, -2),
        (-1, -2),
        (-2, -1),
        (-2, 1),
        (-1, 2),
    ):
        nf = f + df
        nr = r + dr
        if on_board(nf, nr):
            out |= bb(nr * 8 + nf)
    return out


def pawn_attacks_white(sq: int) -> int:
    f = file_of(sq)
    r = rank_of(sq)
    out = 0
    for df in (-1, 1):
        nf = f + df
        nr = r + 1
        if on_board(nf, nr):
            out |= bb(nr * 8 + nf)
    return out


def pawn_attacks_black(sq: int) -> int:
    f = file_of(sq)
    r = rank_of(sq)
    out = 0
    for df in (-1, 1):
        nf = f + df
        nr = r - 1
        if on_board(nf, nr):
            out |= bb(nr * 8 + nf)
    return out


def emit_array(name: str, arr: list[int]) -> None:
    print(f"var {name} = [64]Bitboard{{")
    for i, v in enumerate(arr):
        suffix = ","
        if i == 63:
            suffix = ","
        print(f"\t0x{v:016x}{suffix}")
    print("}")
    print()


def main() -> None:
    print("// Code generated by generate_attack_tables.py; DO NOT EDIT.")
    print("package bitboardchess")
    print()

    emit_array("KnightAttacks", [knight_attacks(sq) for sq in range(64)])
    emit_array("KingAttacks", [king_attacks(sq) for sq in range(64)])
    emit_array("PawnAttacksWhite", [pawn_attacks_white(sq) for sq in range(64)])
    emit_array("PawnAttacksBlack", [pawn_attacks_black(sq) for sq in range(64)])


if __name__ == "__main__":
    main()
